for site in verizon-5g.tlsguru.io ; do
  hey -n 2000 -c 10 -q 2 "https://${site}/"
done

cat <<EOF | kubectl apply -f -
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: kiali-ip-allowlist
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: kiali
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks: ["136.226.166.205/32"]  # Replace with your IP
EOF

Show  cert
istioctl proxy-config secret mike-apache-79fbdf4758-7x2zg -n tls-apache -o json | jq '.dynamicActiveSecrets[0].secret.tlsCertificate.certificateChain.inlineBytes' -r | base64 -d | openssl x509 -text -noout

Show all certs
kubectl get pods -n tls-apache -o jsonpath='{range.items[*]}{.metadata.name}{"\n"}{end}' | xargs -I{} sh -c 'echo "Pod: {}"; istioctl proxy-config secret {} -n tls-apache; echo'

Show containers
kubectl get pods -n tls-apache -o 'custom-columns=POD:.metadata.name,CONTAINERS:.spec.containers[*].name'

kubectl get pod verizon-5g-apache-6b864f5d-l9ndr -n tls-apache -o 'custom-columns=POD:.metadata.name,CONTAINERS:.spec.containers[*].name'