trigger: none


parameters:
- name: cn
  displayName: Common Name
  type: string
  default: "tls.guru"

variables:
- group: Admin Web Request

stages:
- stage: RequestCertificate
  displayName: "Request DigiCert Certificate"
  jobs:
  - job: CallDigiCertAPI
    displayName: "Call DigiCert ONE API"
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Bash@3
      displayName: "Submit Admin Web Request"
      inputs:
        targetType: inline
        script: |
          echo "Requesting certificate for ${{ parameters.cn }}"

          curl --location "$(location)/mpki/api/v1/automation/admin-web-request" \
            --header "Content-Type: application/json" \
            --header "x-api-key: $(api_key)" \
            --data "{
              \"cn\": \"${{ parameters.cn }}\",
              \"profile_id\": \"$(profile_id)\",
              \"account_id\": \"$(account_id)\",
              \"key_size\": \"$(key_size)\",
              \"certificate_services_agreement\": true,
              \"issue_duplicate_cert\": false,
              \"auto_renew_settings\": {
                \"auto_renew_certificate_and_order\": true,
                \"before_expiration\": false,
                \"auto_renew_time\": {
                  \"days\": 1,
                  \"hours\": 12,
                  \"minutes\": 12,
                  \"time_format\": \"AM\",
                  \"zone\": \"Europe/London\"
                }
              },
              \"additional_order_options\": {},
              \"owner_ids\": [],
              \"custom_attributes_field\": [],
              \"cert_delivery_settings\": [
                {
                  \"delivery_method\": \"vault\",
                  \"connector_id\": \"$(connector_id)\",
                  \"vault_ids\": [
                    \"https://nist-keyvault-thylgs.vault.azure.net/\"
                  ]
                }
              ]
            }"